import { StyleSheet, Platform, Dimensions } from 'react-native';
import { colors, typography, commonStyles } from '../theme';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

const styles = StyleSheet.create({
  container: commonStyles.screenContainer,
  scrollContent: commonStyles.scrollContent,
  subHeaderBar: commonStyles.subHeaderBar,
  headerTextGroup: {
    flex: 1,
  },
  subHeaderTitle: commonStyles.subHeaderTitle,
  subHeaderSub: commonStyles.subHeaderSub,
  openShopBtn: {
    backgroundColor: '#FF7E82',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  openShopBtnText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '700',
  },
  pointsBarCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#FFF9E6',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: '#FFEAA7',
    marginBottom: 16,
  },
  pointsBarLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  pointsBarLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#D4AC0D',
  },
  pointsBarValue: {
    fontSize: 16,
    fontWeight: '900',
    color: '#B7950B',
  },
  canvasCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#EBEBEB',
  },
  canvasHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  canvasTitleGroup: {
    flex: 1,
  },
  canvasTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#1C1C1E',
  },
  canvasAreaSubtitle: {
    fontSize: 11,
    fontWeight: '700',
    color: '#FF7E82',
    marginTop: 2,
  },
  logBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EBF5FF',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 14,
  },
  logBtnText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#4A90E2',
  },
  canvasContainer: {
    width: '100%',
    aspectRatio: 1,
    borderRadius: 20,
    overflow: 'hidden',
    position: 'relative',
    backgroundColor: '#F8ECE0',
    borderWidth: 1.5,
    borderColor: '#EFE0D0',
    shadowColor: '#C4A882',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 4,
  },
  roomBgImage: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
  },
  roomActionBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
    flexWrap: 'wrap',
  },
  roomActionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#FFE4D6',
    backgroundColor: '#FFF8F5',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  roomActionBtnBlue: {
    borderColor: '#DBEAFE',
    backgroundColor: '#EFF6FF',
  },
  roomActionBtnEmoji: {
    fontSize: 13,
    marginRight: 4,
  },
  roomActionBtnText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#D9534F',
  },
  roomTouchChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 14,
    borderWidth: 1,
    marginLeft: 'auto',
  },
  roomTouchChipProgress: {
    backgroundColor: '#FFF0F2',
    borderColor: '#FFCCD4',
  },
  roomTouchChipDone: {
    backgroundColor: '#ECFDF5',
    borderColor: '#A7F3D0',
  },
  roomTouchChipTextProgress: {
    fontSize: 11,
    fontWeight: '800',
    color: '#FF4D6D',
  },
  roomTouchChipTextDone: {
    fontSize: 11,
    fontWeight: '800',
    color: '#059669',
  },
  // Dedicated Pet Status Card Below Canvas
  petStatusCardBelow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FAF7F5',
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginTop: 12,
    borderWidth: 1,
    borderColor: '#EFE6DE',
  },
  petStatusCardLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  petStatusMoodWrap: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#FFE0D6',
  },
  petStatusCardName: {
    fontSize: 13,
    fontWeight: '800',
    color: '#1C1C1E',
  },
  petStatusCardLevel: {
    fontSize: 11,
    fontWeight: '800',
    color: '#FF7E82',
  },
  petStatusCardSub: {
    fontSize: 10,
    color: '#8E8E93',
    marginTop: 2,
  },
  petStatusCardRight: {
    minWidth: 95,
  },
  petStatusExpRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  petStatusExpLabel: {
    fontSize: 9.5,
    fontWeight: '700',
    color: '#8E8E93',
  },
  petStatusExpVal: {
    fontSize: 9.5,
    fontWeight: '800',
    color: '#FF7E82',
  },
  petStatusExpBarBg: {
    width: '100%',
    height: 6,
    backgroundColor: '#EAE5E0',
    borderRadius: 3,
    overflow: 'hidden',
  },
  petStatusExpBarFill: {
    height: '100%',
    backgroundColor: '#FF7E82',
    borderRadius: 3,
  },
  themeSelectBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#FFE4D6',
    backgroundColor: '#FFF8F5',
  },
  themeSelectBtnEmoji: {
    fontSize: 12,
    marginRight: 4,
  },
  themeSelectBtnText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#D9534F',
  },
  themeToggleTextNight: {
    fontSize: 9.5,
    fontWeight: '800',
    color: '#D1D8E0',
  },
  floorRug: {
    position: 'absolute',
    top: '60%',
    left: '50%',
    marginLeft: -90,
    width: 180,
    height: 58,
    borderRadius: 29,
    backgroundColor: '#FFE4E9',
    borderWidth: 2,
    borderColor: '#FFCCD6',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 2,
    shadowColor: '#BCA188',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
  },
  floorRugPattern: {
    width: 158,
    height: 40,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: 'rgba(255, 126, 130, 0.35)',
    borderStyle: 'dashed',
  },
  mainCharContainer: {
    position: 'absolute',
    left: '50%',
    marginLeft: -65,
    width: 130,
    top: '45%',
    alignItems: 'center',
    zIndex: 15,
  },
  charGlow: {
    position: 'absolute',
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: 'rgba(255, 230, 235, 0.75)',
    top: -8,
    alignSelf: 'center',
    zIndex: 0,
  },
  charRugPedestal: {
    position: 'absolute',
    bottom: 30,
    width: 120,
    height: 40,
    borderRadius: 60,
    backgroundColor: '#FFE4E8',
    alignSelf: 'center',
    borderWidth: 2,
    borderColor: '#FFCCD4',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
    shadowColor: '#FF7E82',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 5,
  },
  charRugInner: {
    width: 104,
    height: 28,
    borderRadius: 52,
    borderWidth: 1,
    borderColor: 'rgba(255, 126, 130, 0.3)',
    borderStyle: 'dashed',
  },
  charMoodBadge: {
    position: 'absolute',
    top: 30,
    left: -4,
    backgroundColor: '#FFFFFF',
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#FFEAA7',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 3,
    elevation: 3,
    zIndex: 15,
  },
  charMoodEmoji: {
    fontSize: 13,
  },
  mainCharEmojiBubble: {
    width: 105,
    height: 105,
    borderRadius: 52.5,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3.5,
    borderColor: '#FFFFFF',
    shadowColor: '#FF7E82',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
  },
  charTouchArea: {
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  mainCharEmoji: {
    fontSize: 66,
  },
  mainCharImageWrapper: {
    width: 100,
    height: 100,
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
  },
  mainCharImageContainer: {
    width: 100,
    height: 100,
    backgroundColor: 'transparent',
  },
  mainCharImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
    ...(Platform.OS === 'web' ? { mixBlendMode: 'multiply' } : {}),
  },
  charGroundShadow: {
    width: 70,
    height: 10,
    borderRadius: 25,
    backgroundColor: 'rgba(120, 80, 50, 0.16)',
    alignSelf: 'center',
    marginTop: -2,
  },
  charShadow: {
    width: 76,
    height: 10,
    backgroundColor: 'rgba(0,0,0,0.06)',
    borderRadius: 38,
    position: 'absolute',
    bottom: 30,
  },
  mainCharBadge: {
    backgroundColor: 'rgba(255, 255, 255, 0.85)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 14,
    alignItems: 'center',
    marginTop: 4,
    borderWidth: 1,
    borderColor: 'rgba(255, 215, 225, 0.5)',
    shadowColor: '#C4A882',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    elevation: 2,
    zIndex: 10,
  },
  nameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  personalityTag: {
    backgroundColor: '#FFF2F3',
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderRadius: 6,
  },
  personalityTagText: {
    fontSize: 8,
    fontWeight: '800',
    color: '#FF7E82',
  },
  mainCharName: {
    fontSize: 12,
    fontWeight: '800',
    color: '#1C1C1E',
  },
  expBarBg: {
    width: 64,
    height: 5,
    backgroundColor: '#F1F2F4',
    borderRadius: 3,
    overflow: 'hidden',
    marginVertical: 3,
  },
  expBarFill: {
    height: '100%',
    backgroundColor: '#FF7E82',
  },
  levelText: {
    fontSize: 9,
    fontWeight: '700',
    color: '#8E8E93',
  },
  subCharContainer: {
    position: 'absolute',
    alignItems: 'center',
  },
  subCharImageWrapper: {
    width: 34,
    height: 34,
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
  },
  subCharImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
    ...(Platform.OS === 'web' ? { mixBlendMode: 'multiply' } : {}),
  },
  subCharEmoji: {
    fontSize: 28,
  },
  subCharShadow: {
    width: 26,
    height: 6,
    borderRadius: 3,
    backgroundColor: 'rgba(90, 60, 40, 0.15)',
    alignSelf: 'center',
    marginTop: -2,
  },
  subCharLabelBox: {
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    paddingHorizontal: 5,
    paddingVertical: 1.5,
    borderRadius: 6,
    marginTop: 1.5,
    borderWidth: 0.8,
    borderColor: '#EFEFEF',
  },
  subCharLabelText: {
    fontSize: 7.5,
    fontWeight: '700',
    color: '#1C1C1E',
  },
  canvasGuideText: {
    fontSize: 11,
    color: '#8E8E93',
    marginTop: 10,
    lineHeight: 15,
  },
  inventoryCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: '#EBEBEB',
  },
  inventoryTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#1C1C1E',
    marginBottom: 10,
  },
  emptyInventoryText: {
    fontSize: 12,
    color: '#8E8E93',
    fontStyle: 'italic',
    textAlign: 'center',
    paddingVertical: 12,
  },
  inventoryList: {
    flexDirection: 'row',
  },
  inventoryItemChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8F9FA',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 16,
    marginRight: 8,
    borderWidth: 1,
    borderColor: '#EBEBEB',
  },
  inventoryItemChipActive: {
    backgroundColor: '#FFEBEB',
    borderColor: '#FF7E82',
  },
  inventoryItemEmoji: {
    fontSize: 18,
    marginRight: 6,
  },
  inventoryItemName: {
    fontSize: 12,
    fontWeight: '700',
    color: '#1C1C1E',
  },
  // Sumone-Style Fixed Slot Object Styles
  slotObjectWrapper: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    overflow: 'visible',
  },
  slotEquippedContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    overflow: 'visible',
  },
  slotItemImageWrapper: {
    width: 76,
    height: 76,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'transparent',
    overflow: 'visible',
  },
  slotItemImage: {
    width: '100%',
    height: '100%',
    backgroundColor: 'transparent',
    resizeMode: 'contain',
  },
  slotEquippedEmoji: {
    fontSize: 34,
    textShadowColor: 'rgba(0, 0, 0, 0.18)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  slotEquippedLabel: {
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    paddingHorizontal: 6,
    paddingVertical: 1.5,
    borderRadius: 8,
    marginTop: 2,
    borderWidth: 1,
    borderColor: '#EFE0D0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 2,
  },
  slotEquippedLabelText: {
    fontSize: 8.5,
    fontWeight: '800',
    color: '#4A3E3D',
  },
  slotEmptyBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.75)',
    paddingHorizontal: 7,
    paddingVertical: 3.5,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(215, 195, 175, 0.65)',
    borderStyle: 'dashed',
  },
  slotEmptyBadgeText: {
    fontSize: 9,
    fontWeight: '700',
    color: '#8D7B68',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  modalOverlayCenter: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalView: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    maxHeight: '85%',
  },
  modalHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  modalHeaderTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  modalHeader: {
    fontSize: 18,
    fontWeight: '800',
    color: '#1C1C1E',
  },
  modalSubDesc: {
    fontSize: 12,
    color: '#8E8E93',
    marginBottom: 16,
    lineHeight: 18,
  },
  inputGroup: {
    marginBottom: 14,
  },
  modalLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#8E8E93',
    marginBottom: 6,
  },
  modalInput: {
    backgroundColor: '#F1F2F4',
    borderRadius: 10,
    padding: 10,
    fontSize: 13,
    color: '#1C1C1E',
  },
  traitSelectBtn: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 14,
    backgroundColor: '#F1F2F4',
    marginRight: 6,
  },
  traitSelectBtnActive: {
    backgroundColor: '#FF7E82',
  },
  traitSelectText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#1C1C1E',
  },
  traitSelectTextActive: {
    color: '#FFFFFF',
  },
  modalConfirmBtn: {
    backgroundColor: '#FF7E82',
    padding: 14,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 16,
  },
  modalConfirmBtnText: {
    fontSize: 14,
    color: '#FFFFFF',
    fontWeight: '700',
  },
  generatingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(255,255,255,0.95)',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 24,
    padding: 20,
    zIndex: 100,
  },
  generatingText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1C1C1E',
    textAlign: 'center',
    marginTop: 14,
    lineHeight: 20,
  },
  interactModalBox: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 20,
    width: '85%',
    alignItems: 'center',
  },
  interactAvatarBox: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#F8F9FA',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
    borderWidth: 2,
    borderColor: '#EBEBEB',
  },
  interactTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#1C1C1E',
    marginBottom: 4,
  },
  interactDesc: {
    fontSize: 11,
    color: '#8E8E93',
    marginBottom: 16,
    textAlign: 'center',
  },
  interactBtnRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
    marginBottom: 16,
  },
  interactBtnItem: {
    alignItems: 'center',
  },
  interactIconBox: {
    width: 50,
    height: 50,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 6,
  },
  interactBtnText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#1C1C1E',
  },
  closeInteractBtn: {
    backgroundColor: '#F1F2F4',
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 12,
  },
  closeInteractText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#8E8E93',
  },
  categoryTabRow: {
    flexDirection: 'row',
    backgroundColor: '#F1F2F4',
    borderRadius: 10,
    padding: 3,
    marginBottom: 10,
  },
  categoryTab: {
    flex: 1,
    paddingVertical: 7,
    alignItems: 'center',
    borderRadius: 8,
  },
  categoryTabActive: {
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  categoryTabText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#8E8E93',
  },
  categoryTabTextActive: {
    color: '#1C1C1E',
    fontWeight: '800',
  },
  catalogList: {
    maxHeight: 380,
  },
  catalogCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8F9FA',
    borderRadius: 16,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#EBEBEB',
  },
  catalogCardEquipped: {
    backgroundColor: '#F0FDF4',
    borderColor: '#86EFAC',
    borderWidth: 1.5,
  },
  catalogEmojiBox: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
    borderWidth: 1,
    borderColor: '#EBEBEB',
  },
  catalogEmoji: {
    fontSize: 26,
  },
  catalogInfo: {
    flex: 1,
  },
  catalogName: {
    fontSize: 14,
    fontWeight: '800',
    color: '#1C1C1E',
  },
  catalogDesc: {
    fontSize: 11,
    color: '#8E8E93',
    marginTop: 2,
  },
  catalogPrice: {
    fontSize: 13,
    fontWeight: '900',
    color: '#FF7E82',
    marginTop: 4,
  },
  equippedBadge: {
    backgroundColor: '#DCFCE7',
    paddingHorizontal: 6,
    paddingVertical: 1.5,
    borderRadius: 6,
  },
  equippedBadgeText: {
    fontSize: 9,
    fontWeight: '800',
    color: '#15803D',
  },
  unlockedBadge: {
    backgroundColor: '#EBF5FF',
    paddingHorizontal: 6,
    paddingVertical: 1.5,
    borderRadius: 6,
  },
  unlockedBadgeText: {
    fontSize: 9,
    fontWeight: '800',
    color: '#3B82F6',
  },
  slotCurrentBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF8F5',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#FFE4D6',
  },
  slotBannerTitle: {
    fontSize: 12,
    fontWeight: '800',
    color: '#1C1C1E',
  },
  slotBannerSub: {
    fontSize: 10,
    fontWeight: '600',
    color: '#8E8E93',
    marginTop: 1,
  },
  unequipBtn: {
    backgroundColor: '#F1F2F4',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
  },
  unequipBtnText: {
    fontSize: 10.5,
    fontWeight: '700',
    color: '#8E8E93',
  },
  equipBtn: {
    backgroundColor: '#3B82F6',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
  },
  equipBtnText: {
    color: '#FFFFFF',
    fontSize: 11.5,
    fontWeight: '800',
  },
  alreadyEquippedBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#DCFCE7',
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 12,
  },
  alreadyEquippedBtnText: {
    color: '#15803D',
    fontSize: 11,
    fontWeight: '800',
  },
  buyBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FF7E82',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
  },
  buyBtnText: {
    color: '#FFFFFF',
    fontSize: 11.5,
    fontWeight: '800',
  },
  // Touch & Dialogue Interaction Styles (Sumone Style)
  charTouchArea: {
    alignItems: 'center',
    position: 'relative',
  },
  speechBubbleContainer: {
    position: 'absolute',
    bottom: '100%',
    marginBottom: 10,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: '#FF7E82',
    maxWidth: 220,
    minWidth: 140,
    alignItems: 'center',
    shadowColor: '#FF7E82',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 5,
    zIndex: 30,
  },
  speechBubbleText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#2C3E50',
    textAlign: 'center',
    lineHeight: 17,
  },
  speechBubbleArrow: {
    position: 'absolute',
    bottom: -6,
    width: 10,
    height: 10,
    backgroundColor: '#FFFFFF',
    borderRightWidth: 1.5,
    borderBottomWidth: 1.5,
    borderColor: '#FF7E82',
    transform: [{ rotate: '45deg' }],
  },
  floatingHeartContainer: {
    position: 'absolute',
    top: -24,
    alignItems: 'center',
    zIndex: 40,
  },
  touchExpText: {
    fontSize: 11,
    fontWeight: '900',
    color: '#FF4D6D',
    marginTop: 2,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#FFEBEB',
  },
  touchExpTextDone: {
    color: '#FF7E82',
    backgroundColor: '#FFF0F2',
    borderColor: '#FFCCD4',
    fontSize: 10,
    fontWeight: '800',
  },
  touchHintBadge: {
    position: 'absolute',
    top: 30,
    right: -4,
    backgroundColor: '#FF4D6D',
    borderRadius: 10,
    paddingHorizontal: 6,
    paddingVertical: 2,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.15,
    shadowRadius: 2,
    elevation: 2,
    zIndex: 15,
  },
  touchHintBadgeDone: {
    backgroundColor: '#8E8E93',
    borderColor: '#EBEBEB',
  },
  touchHintText: {
    fontSize: 9,
    fontWeight: '900',
    color: '#FFFFFF',
  },
  levelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: 64,
    marginTop: 2,
  },
  expNumberText: {
    fontSize: 8,
    fontWeight: '700',
    color: '#AEAEB2',
  },
  subSpeechBubble: {
    position: 'absolute',
    bottom: '100%',
    marginBottom: 6,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#4A90E2',
    maxWidth: 160,
    minWidth: 100,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    zIndex: 25,
  },
  subSpeechBubbleText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#2C3E50',
    textAlign: 'center',
    lineHeight: 14,
  },
  subSpeechBubbleArrow: {
    position: 'absolute',
    bottom: -5,
    width: 8,
    height: 8,
    backgroundColor: '#FFFFFF',
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#4A90E2',
    transform: [{ rotate: '45deg' }],
  },
  levelUpOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.55)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  levelUpCard: {
    width: '100%',
    maxWidth: 320,
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 24,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 8,
  },
  levelUpEmoji: {
    fontSize: 48,
    marginBottom: 10,
  },
  levelUpTitle: {
    fontSize: 22,
    fontWeight: '900',
    color: '#FF7E82',
    marginBottom: 6,
  },
  levelUpNameText: {
    fontSize: 15,
    fontWeight: '800',
    color: '#1C1C1E',
    marginBottom: 8,
  },
  levelUpDesc: {
    fontSize: 13,
    color: '#636E72',
    textAlign: 'center',
    lineHeight: 18,
    marginBottom: 20,
  },
  levelUpBtn: {
    backgroundColor: '#FF7E82',
    paddingHorizontal: 28,
    paddingVertical: 12,
    borderRadius: 16,
    width: '100%',
    alignItems: 'center',
  },
  levelUpBtnText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '800',
  },
  // Roaming Family Petmong Styles
  roamingCharWrapper: {
    position: 'absolute',
    alignItems: 'center',
    zIndex: 6,
  },
  roamingCharTouch: {
    alignItems: 'center',
  },
  idleEmoteBadge: {
    position: 'absolute',
    top: -14,
    right: -4,
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderWidth: 1,
    borderColor: '#EBEBEB',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  idleEmoteText: {
    fontSize: 10,
  },
  subCharOwnerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 1,
  },
  subCharOwnerAvatar: {
    fontSize: 9,
    marginRight: 2,
  },
  subCharOwnerName: {
    fontSize: 8,
    fontWeight: '700',
    color: '#8E8E93',
  },
  // Foreground Owner Badge
  myCharOwnerBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 126, 130, 0.15)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 126, 130, 0.3)',
    zIndex: 10,
    alignSelf: 'center',
  },
  myCharMoodWrap: {
    marginRight: 4,
    justifyContent: 'center',
    alignItems: 'center',
  },
  myCharOwnerBadgeText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#FF4D6D',
  },
  // Creation Modal Emoji + Buttons
  emojiPickerRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 16,
    justifyContent: 'center',
  },
  emojiPickBtn: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#F8F9FA',
    borderWidth: 1.5,
    borderColor: '#EBEBEB',
    justifyContent: 'center',
    alignItems: 'center',
  },
  emojiPickBtnActive: {
    backgroundColor: '#FFF0F2',
    borderColor: '#FF7E82',
  },
  creationBtnGroup: {
    width: '100%',
    marginTop: 4,
  },
  modalEmojiConfirmBtn: {
    backgroundColor: '#4A90E2',
    borderRadius: 14,
    paddingVertical: 13,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  modalEmojiConfirmBtnText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
  },
  orDividerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 12,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#EBEBEB',
  },
  dividerText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#8E8E93',
    marginHorizontal: 8,
  },
  // Daily Touch Status Chip (Canvas Header)
  dailyStatusChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
    borderWidth: 1,
  },
  dailyStatusChipProgress: {
    backgroundColor: '#FFF0F2',
    borderColor: '#FFCCD4',
  },
  dailyStatusChipDone: {
    backgroundColor: '#ECFDF5',
    borderColor: '#A7F3D0',
  },
  dailyStatusTextProgress: {
    fontSize: 11,
    fontWeight: '800',
    color: '#FF4D6D',
  },
  dailyStatusTextDone: {
    fontSize: 11,
    fontWeight: '800',
    color: '#059669',
  },
  // Resting on Furniture Badge
  restingBadge: {
    backgroundColor: '#FFF9E6',
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: 6,
    marginTop: 2,
    borderWidth: 0.5,
    borderColor: '#FFEAA7',
    alignSelf: 'center',
  },
  restingBadgeText: {
    fontSize: 7.5,
    fontWeight: '700',
    color: '#D48806',
  },
  // Family Petmong Book / Roster Button (Canvas Header)
  familyBookBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EBF5FF',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#D0E7FF',
  },
  familyBookBtnText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#4A90E2',
  },
  // Family Petmong Book Modal Styles
  bookPetCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    padding: 12,
    borderRadius: 16,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#F0F0F2',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 3,
    elevation: 1,
  },
  bookPetCardMine: {
    backgroundColor: '#FFFDFC',
    borderColor: '#FFCCD4',
    borderWidth: 1.5,
  },
  bookPetAvatarBox: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#F8F9FA',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
    overflow: 'hidden',
  },
  bookPetImg: {
    width: 44,
    height: 44,
  },
  bookPetInfo: {
    flex: 1,
  },
  bookPetOwnerName: {
    fontSize: 11,
    fontWeight: '700',
    color: '#8E8E93',
  },
  bookTagMine: {
    backgroundColor: '#FFEBEB',
    paddingHorizontal: 6,
    paddingVertical: 1.5,
    borderRadius: 6,
  },
  bookTagMineText: {
    fontSize: 9,
    fontWeight: '800',
    color: '#FF7E82',
  },
  bookTagRoaming: {
    backgroundColor: '#EBF5FF',
    paddingHorizontal: 6,
    paddingVertical: 1.5,
    borderRadius: 6,
  },
  bookTagRoamingText: {
    fontSize: 9,
    fontWeight: '800',
    color: '#4A90E2',
  },
  bookTagResting: {
    backgroundColor: '#FFF9E6',
    paddingHorizontal: 6,
    paddingVertical: 1.5,
    borderRadius: 6,
  },
  bookTagRestingText: {
    fontSize: 9,
    fontWeight: '800',
    color: '#D48806',
  },
  bookPetName: {
    fontSize: 14,
    fontWeight: '800',
    color: '#1C1C1E',
  },
  bookPetLevel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#8E8E93',
  },
  bookPetPersonalityTag: {
    backgroundColor: '#F2F2F7',
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderRadius: 6,
  },
  bookPetPersonalityText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#636E72',
  },
  bookExpBarBg: {
    width: '80%',
    height: 4,
    backgroundColor: '#F2F2F7',
    borderRadius: 2,
    marginTop: 5,
    overflow: 'hidden',
  },
  bookExpBarFill: {
    height: '100%',
    backgroundColor: '#FF7E82',
  },
  bookInteractBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFEBEB',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
    marginLeft: 8,
  },
  bookInteractBtnText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#FF4D6D',
  },
  // Room Theme Selection Modal Styles
  themeCardItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 14,
    borderRadius: 16,
    backgroundColor: '#F8F9FA',
    borderWidth: 1.5,
    borderColor: '#EFEFEF',
  },
  themeCardItemActive: {
    backgroundColor: '#FFF5F5',
    borderColor: '#FF7E82',
  },
  themeCardIconWrap: {
    width: 46,
    height: 46,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
    borderWidth: 1,
    borderColor: '#EFEFEF',
  },
  themeCardTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#1C1C1E',
  },
  themeCardDesc: {
    fontSize: 11,
    color: '#8E8E93',
    marginTop: 2,
  },
  themeSelectedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FF7E82',
    paddingHorizontal: 6,
    paddingVertical: 1.5,
    borderRadius: 6,
  },
  themeSelectedBadgeText: {
    fontSize: 9,
    fontWeight: '800',
    color: '#FFFFFF',
  },

  // Fullscreen Room Layout Styles
  fullscreenContainer: {
    flex: 1,
    width: '100%',
    height: '100%',
    position: 'relative',
    backgroundColor: '#F8ECE0',
    overflow: 'hidden',
  },
  fullscreenBg: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
  },
  fullscreenOverlayCanvas: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
  },

  // Top Floating Header Bar
  topFloatingHeader: {
    position: 'absolute',
    top: 10,
    left: 12,
    right: 12,
    zIndex: 100,
    backgroundColor: 'rgba(255, 255, 255, 0.94)',
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.7)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 4,
  },
  familyTabsScroll: {
    flex: 1,
    marginRight: 8,
  },
  familyTabsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  familyRoomChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
    backgroundColor: '#F3F4F6',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  familyRoomChipActive: {
    backgroundColor: '#FF7E82',
    borderColor: '#FF7E82',
  },
  familyRoomChipAvatar: {
    fontSize: 13,
    marginRight: 4,
  },
  familyRoomChipText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#4B5563',
  },
  familyRoomChipTextActive: {
    color: '#FFFFFF',
  },
  familyRoomBadgeDot: {
    backgroundColor: '#10B981',
    borderRadius: 8,
    paddingHorizontal: 5,
    paddingVertical: 1,
    marginLeft: 4,
  },
  familyRoomBadgeDotText: {
    fontSize: 9,
    fontWeight: '900',
    color: '#FFFFFF',
  },
  topActionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  topActionIconBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 12,
    backgroundColor: '#FFF8F5',
    borderWidth: 1,
    borderColor: '#FFE4D6',
  },
  topActionIconBtnBlue: {
    backgroundColor: '#EFF6FF',
    borderColor: '#DBEAFE',
  },
  topActionBtnText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#D9534F',
    marginLeft: 3,
  },

  // Idle Drop Bubbles (Clean Transparent Icons without background circle)
  bubbleContainer: {
    position: 'absolute',
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 80,
  },
  bubbleTouchable: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  bubbleIconWrapper: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  bubbleFloatParticle: {
    position: 'absolute',
    top: -24,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  bubbleFloatParticleText: {
    fontSize: 11,
    fontWeight: '900',
  },

  // Bottom Floating Glass HUD
  bottomFloatingHud: {
    position: 'absolute',
    left: 14,
    right: 14,
    zIndex: 100,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 22,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.8)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12,
    shadowRadius: 14,
    elevation: 6,
  },
  // Collapsed Mini Floating Capsule
  hudMiniCapsule: {
    position: 'absolute',
    alignSelf: 'center',
    zIndex: 100,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.92)',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.9)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 5,
    gap: 8,
  },
  hudMiniPetBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  hudMiniPetName: {
    fontSize: 12.5,
    fontWeight: '800',
    color: '#1F2937',
  },
  hudMiniLevelBadge: {
    backgroundColor: '#FFEBEB',
    paddingHorizontal: 5,
    paddingVertical: 1.5,
    borderRadius: 6,
  },
  hudMiniLevelText: {
    fontSize: 10.5,
    fontWeight: '800',
    color: '#FF7E82',
  },
  hudMiniDivider: {
    width: 1,
    height: 12,
    backgroundColor: '#E5E7EB',
  },
  hudMiniHarvestBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  hudMiniHarvestText: {
    fontSize: 11.5,
    fontWeight: '700',
    color: '#374151',
  },
  hudMiniHarvestMaxBadge: {
    backgroundColor: '#D1FAE5',
    paddingHorizontal: 5,
    paddingVertical: 1,
    borderRadius: 5,
  },
  hudMiniHarvestMaxText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#059669',
  },
  hudMiniToggleArrow: {
    marginLeft: 2,
  },
  hudCollapseToggleBtn: {
    padding: 4,
    borderRadius: 12,
    backgroundColor: '#F3F4F6',
  },
  hudTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  hudPetInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  hudMoodWrap: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: '#FFE0D6',
  },
  hudPetName: {
    fontSize: 14,
    fontWeight: '800',
    color: '#1C1C1E',
  },
  hudPetLevel: {
    fontSize: 11,
    fontWeight: '800',
    color: '#FF7E82',
  },
  hudOwnerSub: {
    fontSize: 10,
    color: '#8E8E93',
    marginTop: 1,
  },
  hudExpBox: {
    minWidth: 100,
  },
  hudExpRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 3,
  },
  hudExpLabel: {
    fontSize: 9.5,
    fontWeight: '700',
    color: '#8E8E93',
  },
  hudExpValue: {
    fontSize: 9.5,
    fontWeight: '800',
    color: '#FF7E82',
  },
  hudExpBarBg: {
    width: '100%',
    height: 6,
    borderRadius: 3,
    backgroundColor: '#EAE5E0',
    overflow: 'hidden',
  },
  hudExpBarFill: {
    height: '100%',
    borderRadius: 3,
    backgroundColor: '#FF7E82',
  },
  hudDivider: {
    height: 1,
    backgroundColor: '#F3F4F6',
    marginVertical: 8,
  },
  hudBottomRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  hudHarvestProgressCol: {
    flex: 1,
    marginRight: 10,
  },
  hudHarvestProgressHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  hudHarvestProgressTitle: {
    fontSize: 11.5,
    fontWeight: '800',
    color: '#374151',
  },
  hudHarvestProgressSub: {
    fontSize: 10,
    color: '#8E8E93',
    marginTop: 2,
  },
  hudHarvestAllBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FF7E82',
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 14,
    shadowColor: '#FF7E82',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 2,
  },
  hudHarvestAllBtnText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '800',
    marginLeft: 4,
  },
  hudTouchBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
    backgroundColor: '#FFF0F2',
    borderWidth: 1,
    borderColor: '#FFCCD4',
  },
  hudTouchBtnDone: {
    backgroundColor: '#ECFDF5',
    borderColor: '#A7F3D0',
  },
  hudTouchBtnText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#FF4D6D',
    marginLeft: 4,
  },
  hudTouchBtnTextDone: {
    color: '#059669',
  },
  visitingBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FEF3C7',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    marginBottom: 6,
    alignSelf: 'flex-start',
  },
  visitingBannerText: {
    fontSize: 10.5,
    fontWeight: '700',
    color: '#92400E',
    marginLeft: 4,
  },
  createPromptBanner: {
    position: 'absolute',
    top: '40%',
    alignSelf: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderRadius: 18,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#FFCCD4',
    shadowColor: '#FF7E82',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 5,
    zIndex: 90,
  },
  createPromptTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#1C1C1E',
    marginBottom: 4,
  },
  createPromptSub: {
    fontSize: 12,
    color: '#8E8E93',
    textAlign: 'center',
    marginBottom: 12,
  },
  createPromptBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FF7E82',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 14,
  },
  createPromptBtnText: {
    fontSize: 13,
    fontWeight: '800',
    color: '#FFFFFF',
    marginLeft: 4,
  },
  // Character Evolution & Aura Styles
  charStageBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 7,
    paddingVertical: 2.5,
    borderRadius: 10,
    marginTop: 3,
    alignSelf: 'center',
  },
  charStageBadgeText: {
    fontSize: 9.5,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  guardianAuraRing: {
    position: 'absolute',
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 2,
    borderColor: 'rgba(250, 173, 20, 0.45)',
    backgroundColor: 'rgba(255, 241, 184, 0.2)',
    alignSelf: 'center',
    top: -10,
    zIndex: -1,
  },
  starAuraSparkle: {
    position: 'absolute',
    top: -6,
    right: 8,
  },
  // Evolution Celebration Modal Styles
  evolutionOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.65)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  evolutionCard: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 22,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#FFE58F',
    shadowColor: '#FAAD14',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 16,
    elevation: 8,
  },
  evolutionHeaderEmoji: {
    fontSize: 38,
    marginBottom: 6,
  },
  evolutionTitle: {
    fontSize: 21,
    fontWeight: '900',
    color: '#1C1C1E',
    letterSpacing: -0.3,
  },
  evolutionStagePill: {
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 14,
    marginTop: 8,
    marginBottom: 16,
  },
  evolutionStagePillText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  evolutionComparisonRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    marginVertical: 10,
    width: '100%',
  },
  evolutionPreviewBox: {
    alignItems: 'center',
    padding: 10,
    borderRadius: 16,
    backgroundColor: '#F9F9FB',
    borderWidth: 1.5,
    borderColor: '#EFEFEF',
    minWidth: 100,
  },
  evolutionPreviewBoxActive: {
    backgroundColor: '#FFFBE6',
    borderColor: '#FFE58F',
  },
  evolutionPreviewLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#8E8E93',
    marginBottom: 6,
  },
  evolutionPreviewEmoji: {
    fontSize: 36,
  },
  evolutionGeneratingBox: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 16,
    backgroundColor: '#FFF0F6',
    borderWidth: 1.5,
    borderColor: '#FFADD2',
    marginVertical: 10,
    width: '100%',
  },
  evolutionGeneratingText: {
    fontSize: 12.5,
    fontWeight: '700',
    color: '#EB2F96',
    marginTop: 8,
    textAlign: 'center',
  },
  evolutionDesc: {
    fontSize: 12.5,
    color: '#636366',
    textAlign: 'center',
    lineHeight: 18,
    marginVertical: 12,
  },
  evolutionBonusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F6FFED',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#B7EB8F',
    marginBottom: 16,
  },
  evolutionBonusText: {
    fontSize: 11.5,
    fontWeight: '700',
    color: '#389E0D',
    marginLeft: 4,
  },
  evolutionConfirmBtn: {
    width: '100%',
    backgroundColor: '#FF7E82',
    paddingVertical: 14,
    borderRadius: 16,
    alignItems: 'center',
    shadowColor: '#FF7E82',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 3,
  },
  evolutionConfirmBtnText: {
    fontSize: 15,
    fontWeight: '800',
    color: '#FFFFFF',
  },
});

export default styles;
